services:
  # Express API service
  - type: web
    name: lawxpert-express
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: CONNECTION_STRING
        fromGroup: lawxpert-env
    routes:
      - type: rewrite
        source: /api/*
        destination: /*

  # Python FastAPI service  
  - type: web
    name: lawxpert-python
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GEMINI_API_KEY
        fromGroup: lawxpert-env
    routes:
      - type: rewrite
        source: /analyze
        destination: /analyze

# Shared environment variables group
envVarGroups:
  - name: lawxpert-env
    envVars:
      - key: CONNECTION_STRING
        sync: false
      - key: GEMINI_API_KEY
        sync: false 